-- This file was generated by the Reassembly Web Development Kit (RWDK)
-- RWDK is an independent project and in no way affiliated with Anisoptera Games.
-- RWDK was written by TTFTCUTS

{
	19000 = {
		name="Avalon Draconis Concord",
		playable=2,
		start="19000_Corvette",
		primaries=3,
		color0=0x12557a,
		color1=0x23232b,
		color2=0xff9200,
	},

}
