-- This file was generated by the Reassembly Web Development Kit (RWDK)
-- RWDK is an independent project and in no way affiliated with Anisoptera Games.
-- RWDK was written by TTFTCUTS

{
	ident=1900,
	color=0x17577a,
	faction=19000,
	count=5,
	position={0.1, 0.8},
	radius={0.07, 0.15},
	type=1,
	fleets={
		{19000, { {0, 9000}, {1, 6000} }},
	},
	fleetCount={2, 7},
	fleetFraction=0.985,
	fortress={
		"19000_Corvette",
		"19000_Heavy Corvette",
		"19000_Bomber",
		"19000_Light Cruiser",
		"19000_Frigate",
	},
	fortressCount={2, 4},
	fortressRadius={750, 1250},
	unique={
		{
			"19000_Battlecruiser",
			"19000_Sector Command Fortress",
			"19000_Flagship",
			"19000_Carrier",
			"19000_Armoured Cruiser",
		},
	},
	uniqueFraction=0.015,
	ambient={ 0 },
	asteroidDensity={0.05, 0.4},
	asteroidSize={5, 30},
	asteroidFlags=TRIANGLE,
},

